# Generated by Django 3.0.7 on 2020-06-16 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('city', models.IntegerField(choices=[(0, 'Mumbai'), (1, 'Delhi'), (2, 'Kolkata'), (3, 'Chennai'), (4, 'Bengalūru'), (5, 'Hyderabad'), (6, 'Ahmadābād'), (7, 'Hāora'), (8, 'Pune'), (9, 'Sūrat'), (10, 'Cawnpore'), (11, 'Jaipur'), (12, 'Lucknow'), (13, 'Nāgpur'), (14, 'Patna'), (15, 'Indore'), (16, 'Vadodara'), (17, 'Bhopal'), (18, 'Coimbatore'), (19, 'Ludhiāna'), (20, 'Āgra'), (21, 'Kalyān'), (22, 'Vishākhapatnam'), (23, 'Kochi'), (24, 'Nāsik'), (25, 'Meerut'), (26, 'Farīdābād'), (27, 'Vārānasi'), (28, 'Ghāziābād'), (29, 'Āsansol'), (30, 'Jamshedpur'), (31, 'Madura'), (32, 'Jabalpur'), (33, 'Rājkot'), (34, 'Dhanbād'), (35, 'Amritsar'), (36, 'Warangal'), (37, 'Allahābād'), (38, 'Srīnagar'), (39, 'Bezwāda'), (40, 'Aurangābād'), (41, 'Bhilai'), (42, 'Solāpur'), (43, 'Ranchi'), (44, 'New Delhi'), (45, 'Jodhpur'), (46, 'Guwāhāti'), (47, 'Chandigarh'), (48, 'Gwalior'), (49, 'Thiruvananthapuram'), (50, 'Calicut'), (51, 'Trichinopoly'), (52, 'Hubli'), (53, 'Mysore'), (54, 'Raipur'), (55, 'Salem'), (56, 'Jalandhar'), (57, 'Bhubaneshwar'), (58, 'Kota'), (59, 'Jhānsi'), (60, 'Bareilly'), (61, 'Alīgarh'), (62, 'Bhiwandi'), (63, 'Jammu'), (64, 'Morādābād'), (65, 'Mangalore'), (66, 'Kolhāpur'), (67, 'Amrāvati'), (68, 'Dehra Dūn'), (69, 'Mālegaon'), (70, 'Nellore'), (71, 'Gorakhpur'), (72, 'Shimoga'), (73, 'Tiruppūr'), (74, 'Raurkela'), (75, 'Nānded'), (76, 'Belgaum'), (77, 'Sāngli'), (78, 'Chānda'), (79, 'Ajmer'), (80, 'Cuttack'), (81, 'Bīkaner'), (82, 'Bhāvnagar'), (83, 'Hisar'), (84, 'Bilāspur'), (85, 'Tinnevelly'), (86, 'Guntūr'), (87, 'Shiliguri'), (88, 'Ujjain'), (89, 'Davangere'), (90, 'Akola'), (91, 'Sahāranpur'), (92, 'Gulbarga'), (93, 'Bhātpāra'), (94, 'Dhūlia'), (95, 'Udaipur'), (96, 'Bellary'), (97, 'Tuticorin'), (98, 'Kurnool'), (99, 'Gaya'), (100, 'Sīkar'), (101, 'Tumkūr'), (102, 'Quilon'), (103, 'Ahmadnagar'), (104, 'Bhīlwāra'), (105, 'Nizāmābād'), (106, 'Parbhani'), (107, 'Shillong'), (108, 'Lātūr'), (109, 'Rājapālaiyam'), (110, 'Bhāgalpur'), (111, 'Muzaffarnagar'), (112, 'Muzaffarpur'), (113, 'Mathura'), (114, 'Patiāla'), (115, 'Saugor'), (116, 'Brahmapur'), (117, 'Shāhjānpur'), (118, 'Rohtak'), (119, 'Sambalpur'), (120, 'Ratlām'), (121, 'Fīrozābād'), (122, 'Rājahmundry'), (123, 'Barddhamān'), (124, 'Bīdar'), (125, 'Rāmpur'), (126, 'Kākināda'), (127, 'Pānīpat'), (128, 'Khammam'), (129, 'Bhuj'), (130, 'Karīmnagar'), (131, 'Tirupati'), (132, 'Hospet'), (133, 'Mandya'), (134, 'Alwar'), (135, 'Aizawl'), (136, 'Bijāpur'), (137, 'Imphal'), (138, 'Etāwah'), (139, 'Rāichūr'), (140, 'Pathānkot'), (141, 'Chīrāla'), (142, 'Sonīpat'), (143, 'Mirzāpur'), (144, 'Hāpur'), (145, 'Porbandar'), (146, 'Bharatpur'), (147, 'Puducherry'), (148, 'Karnāl'), (149, 'Nāgercoil'), (150, 'Tanjore'), (151, 'Pāli'), (152, 'Agartala'), (153, 'Ongole'), (154, 'Puri'), (155, 'Dindigul'), (156, 'Haldia'), (157, 'Bulandshahr'), (158, 'Purnea'), (159, 'Proddatūr'), (160, 'Gurgaon'), (161, 'Burhānpur'), (162, 'Ghandinagar'), (163, 'Machilīpatnam'), (164, 'Bhiwāni'), (165, 'Nandyāl'), (166, 'Bhusāval'), (167, 'Bahraigh'), (168, 'Tonk'), (169, 'Sirsa'), (170, 'Vizianagaram'), (171, 'Vellore'), (172, 'Alleppey'), (173, 'Shimla'), (174, 'Medinīpur'), (175, 'Hindupur'), (176, 'Bāramūla'), (177, 'Fatehpur'), (178, 'Dibrugarh'), (179, 'Sitalpur'), (180, 'Navsāri'), (181, 'Budaun'), (182, 'Cuddalore'), (183, 'Harīpur'), (184, 'Conjeeveram'), (185, 'Fyzābād'), (186, 'Silchar'), (187, 'Ambāla'), (188, 'Krishnanagar'), (189, 'Kolār'), (190, 'Kumbakonam'), (191, 'Tiruvannāmalai'), (192, 'Pīlibhīt'), (193, 'Abohar'), (194, 'Port Blair'), (195, 'Alīpur Duār'), (196, 'Hāthras'), (197, 'Vālpārai'), (198, 'Kohima'), (199, 'Gangtok'), (200, 'Panaji'), (201, 'Itanagar'), (202, 'Daman'), (203, 'Silvassa'), (204, 'Dispur'), (205, 'Kavaratti'), (206, 'Aurangābād'), (207, 'Karūr'), (208, 'Jorhāt'), (209, 'Sopur'), (210, 'Tezpur'), (211, 'Diu'), (212, 'Vancouver')])),
                ('number_queries', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel_id', models.CharField(max_length=25)),
                ('Channel_name', models.CharField(max_length=55)),
                ('Channel_subscribers', models.IntegerField()),
                ('Channel_views', models.IntegerField()),
                ('Channel_query', models.CharField(max_length=100)),
                ('Channel_city', models.CharField(max_length=100)),
                ('Channel_video_count', models.IntegerField()),
            ],
            options={
                'unique_together': {('Channel_id', 'Channel_query', 'Channel_city')},
            },
        ),
    ]
